#!/bin/sh

staged () {
    git show ":$1"
}

VERSION=$(sed -n 's/(version \(.*\)\.[0-9]\+)/\1/p' dune-project)
VERSION="V${VERSION//./_}"

check () {
    if ! staged "$1" | grep -q "$VERSION"; then
        echo "missing module $VERSION in $1" 1>&2
        exit 1
    fi
}

check "timmy/lib/src/timmy.ml"
check "timmy/lib/src/versions.ml"
check "timmy-jsoo/lib/src/timmy_jsoo.ml"
check "timmy-jsoo/lib/src/versions.ml"
