include:
  - local: "/.logistic/ci/dune/.gitlab-ci.yml"

documentation:
  extends: .ocaml
  stage: build
  needs:
    - build
  script:
    - dune build @doc
  artifacts:
    expire_in: 10 days
    paths:
      - _build/default/_doc/_html
    
publish-documentation:
  extends:
    - .ocaml-opam
  needs:
    - documentation
  script:
    - ./doc-publish
