include:
  - local: '/.logistic/ci/dune/.gitlab-ci-template.yml'

build:
  extends: .ocaml-build

build:no-schematic:
  extends: .ocaml-build
  variables:
    WORKSPACE: "no-schematic"
    
opam:
  extends: .ocaml-opam
  needs:
    - build
    - build:no-schematic
