include:
  - local: "/.logistic/ci/.gitlab-ci-template.yml"

toolchain:
  extends: .ocaml-toolchain
  variables:
    OCAML_VERSION: "4.12.0"
    OPAM_PACKAGES: "js_of_ocaml schematic"
    PACKAGES: "nodejs npm"

toolchain:no-schematic:
  extends: .ocaml-toolchain
  variables:
    OCAML_VERSION: "4.12.0"
    OPAM_PACKAGES: "js_of_ocaml"
    OPAM_WITHOUT_PACKAGES: "schematic"
    VARIANT: "-no-schematic"
    PACKAGES: "nodejs npm"

toolchain:no-jsoo:
  extends: .ocaml-toolchain
  variables:
    OCAML_VERSION: "4.12.0"
    OPAM_PACKAGES: "schematic"
    OPAM_WITHOUT_PACKAGES: "js_of_ocaml"
    VARIANT: "-no-jsoo"
    PACKAGES: "nodejs npm"

build:
  extends: .ocaml-build
  dependencies:
    - toolchain
  needs:
    - toolchain

build:no-schematic:
  extends: .ocaml-build
  dependencies:
    - toolchain:no-schematic
  needs:
    - toolchain:no-schematic
  variables:
    OCAML_VERSION: "4.12.0"
    VARIANT: "-no-schematic"

build:no-jsoo:
  extends: .ocaml-build
  dependencies:
    - toolchain:no-jsoo
  needs:
    - toolchain:no-jsoo
  variables:
    OCAML_VERSION: "4.12.0"
    VARIANT: "-no-jsoo"

check:
  extends: .ocaml-check
  dependencies:
    - build
  needs:
    - build

check:no-schematic:
  extends: .ocaml-check
  dependencies:
    - build:no-schematic
  needs:
    - build:no-schematic
  variables:
    OCAML_VERSION: "4.12.0"
    VARIANT: "-no-schematic"

check:no-jsoo:
  extends: .ocaml-check
  dependencies:
    - build:no-jsoo
  needs:
    - build:no-jsoo
  variables:
    OCAML_VERSION: "4.12.0"
    VARIANT: "-no-jsoo"

package:
  extends: .ocaml-package
  dependencies:
    - check
  needs:
    - check
    - check:no-schematic
    - check:no-jsoo

opam:
  extends: .ocaml-opam
  dependencies:
    - check
  needs:
    - check
    - check:no-schematic
    - check:no-jsoo
