include:
  - local: "/.logistic/ci/.gitlab-ci-template.yml"

toolchain:
  extends: .toolchain

toolchain:no-schematic:
  extends: .toolchain
  variables:
    DUNE_PACKAGES: "timmy,timmy-lwt,timmy-unix"
    OPAM_WITHOUT_PACKAGES: "schematic"
    VARIANT: "-no-schematic"

build:
  extends: .ocaml-build
  dependencies:
    - toolchain
  needs:
    - toolchain

build:no-schematic:
  extends: .ocaml-build
  dependencies:
    - toolchain:no-schematic
  needs:
    - toolchain:no-schematic
  variables:
    DUNE_PACKAGES: "timmy,timmy-unix"
    VARIANT: "-no-schematic"

documentation:
  extends: .ocaml
  stage: build
  dependencies:
    - toolchain
  needs:
    - toolchain
  script:
    - opam exec -- dune build @doc
  artifacts:
    expire_in: 10 days
    paths:
      - _build/default/_doc/_html

check:
  extends: .ocaml-check
  dependencies:
    - build
  needs:
    - build

check:no-schematic:
  extends: .ocaml-check
  dependencies:
    - build:no-schematic
  needs:
    - build:no-schematic
  variables:
    VARIANT: "-no-schematic"

package:
  extends: .ocaml-package
  dependencies:
    - check
  needs:
    - check
    - check:no-schematic

publish:
  extends:
    - .ocaml-opam
  dependencies:
    - check
    - documentation
  needs:
    - check
    - check:no-schematic
    - documentation
  script:
    - !reference [.ocaml-opam, script]
    - ./doc-publish
