include:
  - local: "/.logistic/ci/.gitlab-ci-template.yml"

toolchain:
  extends: .ocaml-toolchain
  variables:
    OPAM_PACKAGES: "js_of_ocaml schematic-jsoo"

toolchain:no-schematic:
  extends: .ocaml-toolchain
  variables:
    OPAM_PACKAGES: "js_of_ocaml"
    OPAM_WITHOUT_PACKAGES: "schematic"
    VARIANT: "-no-schematic"

toolchain:no-jsoo:
  extends: .ocaml-toolchain
  variables:
    OPAM_PACKAGES: "schematic"
    OPAM_WITHOUT_PACKAGES: "js_of_ocaml"
    DUNE_PACKAGES: "timmy"
    VARIANT: "-no-jsoo"

build:
  extends: .ocaml-build
  before_script:
    # Dune can't selectively disable an executable
    - echo '(dirs bin lib)' > 'timmy-jsoo/dune'
  dependencies:
    - toolchain
  needs:
    - toolchain

build:no-schematic:
  extends: .ocaml-build
  before_script:
    # Dune can't selectively disable an executable
    - echo '(dirs lib)' > 'timmy-jsoo/dune'
  dependencies:
    - toolchain:no-schematic
  needs:
    - toolchain:no-schematic
  variables:
    VARIANT: "-no-schematic"

build:no-jsoo:
  extends: .ocaml-build
  before_script:
    # Dune can't selectively disable an executable
    - echo '(dirs bin lib)' > 'timmy-jsoo/dune'
  dependencies:
    - toolchain:no-jsoo
  needs:
    - toolchain:no-jsoo
  variables:
    DUNE_PACKAGES: "timmy"
    VARIANT: "-no-jsoo"

documentation:
  extends: .ocaml
  stage: build
  dependencies:
    - toolchain
  needs:
    - toolchain
  script:
    - opam exec -- dune build @doc
  artifacts:
    expire_in: 10 days
    paths:
      - _build/default/_doc/_html

check:
  extends: .ocaml-check
  dependencies:
    - build
  needs:
    - build

check:no-schematic:
  extends: .ocaml-check
  before_script:
    # Dune can't selectively disable an executable
    - echo '(dirs lib)' > 'timmy-jsoo/dune'
  dependencies:
    - build:no-schematic
  needs:
    - build:no-schematic
  variables:
    VARIANT: "-no-schematic"

check:no-jsoo:
  extends: .ocaml-check
  dependencies:
    - build:no-jsoo
  needs:
    - build:no-jsoo
  variables:
    VARIANT: "-no-jsoo"

package:
  extends: .ocaml-package
  dependencies:
    - check
  needs:
    - check
    - check:no-schematic
    - check:no-jsoo

publish:
  extends:
    - .ocaml-opam
  dependencies:
    - check
    - documentation
  needs:
    - check
    - check:no-schematic
    - check:no-jsoo
    - documentation
  script:
    - !reference [.ocaml-opam, script]
    - ./doc-publish
