stages:
  - environment
  - build
  - check
  - package
  - deploy

before_script:
  - which docker && echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" --username "$CI_REGISTRY_USER" --password-stdin
  - test -e "yarn.lock" && apk add --no-cache yarn && yarn
  - test -n "$PACKAGES" && apk add --no-cache $PACKAGES

variables:
  BRANCH: "$CI_COMMIT_REF_NAME"
  IMAGE: "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
  SLUG: "$CI_COMMIT_REF_SLUG"
  DUNE_CACHE_STORAGE_MODE: "copy"

.ocaml:
  image: "$CI_REGISTRY/routine/logistic/dune-builder:dc1df56"

.ocaml-build:
  extends: .ocaml
  stage: build
  script:
    - make -f .logistic/ci/dune/Makefile lint
    - make -f .logistic/ci/dune/Makefile build
    - make -f .logistic/ci/dune/Makefile check
    - make -f .logistic/ci/dune/Makefile package

.ocaml-opam:
  extends: .ocaml
  stage: package
  script:
    - make -f .logistic/ci/dune/Makefile opam
  rules:
    - if: '$CI_COMMIT_TAG =~ /[0-9]+\.[0-9]+\.[0-9]+/'
