stages:
  - build

before_script:
  - apk add --no-cache docker-cli make
  - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" --username "$CI_REGISTRY_USER" --password-stdin

opam-builder:
  stage: build
  only:
    - master
  script:
    - docker build -f docker/opam-builder/Dockerfile docker/opam-builder -t $CI_REGISTRY_IMAGE/ci-builder
    - docker push $CI_REGISTRY_IMAGE/ci-builder

dune-builder:
  stage: build
  script:
    - make dune-builder
