stages:
  - environment
  - build
  - check

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" --username "$CI_REGISTRY_USER" --password-stdin

.ocaml-build-image:
  stage: environment
  image: registry.gitlab.routine.co/routine/logistic/ci-builder
  script:
    - |
      make -f .logistic/ci/Makefile ci/image                            \
      REGISTRY=$CI_REGISTRY                                             \
      NAMESPACE=$CI_PROJECT_NAMESPACE                                   \
      PROJECT=$CI_PROJECT_NAME                                          \
      OCAML_VERSION=$OCAML_VERSION
    - docker push "$CI_REGISTRY_IMAGE/ci:$OCAML_VERSION"
  variables:
    OCAML_VERSION: "4.10.0"

.ocaml-build:
  stage: build
  image: $CI_REGISTRY_IMAGE/ci:$OCAML_VERSION
  script:
    - make -f .logistic/ci/Makefile build
  artifacts:
    paths:
      - _build/
  variables:
    OCAML_VERSION: "4.10.0"

.ocaml-check:
  stage: check
  image: $CI_REGISTRY_IMAGE/ci:$OCAML_VERSION
  script:
    - make -f .logistic/ci/Makefile check
  variables:
    OCAML_VERSION: "4.10.0"
