include:
  - local: '/.logistic/ci/.gitlab-ci.yml'

build-image:4.06:
  extends: .ocaml-build-image
  variables:
    OCAML_VERSION: "4.06.0"

build-image:4.10:
  extends: .ocaml-build-image

build:4.06:
  extends: .ocaml-build
  dependencies:
    - build-image:4.06
  needs:
    - build-image:4.06
  variables:
    OCAML_VERSION: "4.06.0"

build:4.10:
  extends: .ocaml-build
  dependencies:
    - build-image:4.10
  needs:
    - build-image:4.10

check:4.06:
  extends: .ocaml-check
  dependencies:
    - build:4.06
  needs:
    - build:4.06
  variables:
    OCAML_VERSION: "4.06.0"

check:4.10:
  extends: .ocaml-check
  dependencies:
    - build:4.10
  needs:
    - build:4.10
