stages:
  - environment
  - build
  - check
  - package
  - deploy

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" --username "$CI_REGISTRY_USER" --password-stdin

variables:
  REGISTRY: "$CI_REGISTRY"
  NAMESPACE: "$CI_PROJECT_NAMESPACE"
  PROJECT: "$CI_PROJECT_NAME"
  BRANCH: "$CI_COMMIT_REF_NAME"
  SLUG: "$CI_COMMIT_REF_SLUG"

.docker:
  image: registry.gitlab.routine.co/routine/logistic/ci-builder

.ocaml:
  image: $CI_REGISTRY_IMAGE/ci:$OCAML_VERSION

.ocaml-build-image:
  extends: .docker
  stage: environment
  image: registry.gitlab.routine.co/routine/logistic/ci-builder
  script:
    - |
      make -f .logistic/ci/Makefile ci/image                            \
      OCAML_VERSION=$OCAML_VERSION                                      \
      PACKAGES=$PACKAGES
    - docker push "$CI_REGISTRY_IMAGE/ci:$OCAML_VERSION"
  variables:
    OCAML_VERSION: "4.10.0"

.ocaml-build:
  extends: .ocaml
  stage: build
  script:
    - make -f .logistic/ci/Makefile build
  artifacts:
    paths:
      - _build/
  variables:
    OCAML_VERSION: "4.10.0"

.ocaml-check:
  extends: .ocaml
  stage: check
  script:
    - make -f .logistic/ci/Makefile check
  artifacts:
    paths:
      - _build/
  variables:
    OCAML_VERSION: "4.10.0"

.ocaml-package:
  extends: .ocaml
  stage: package
  script:
    - make -f .logistic/ci/Makefile package
  after_script:
    - make -f .logistic/ci/Makefile package/clean
  artifacts:
    reports:
      metrics: metrics.txt
  variables:
    OCAML_VERSION: "4.10.0"
